export const ANNIVERSARY_LIST = 'ANNIVERSARY_LIST'
export const ANNIVERSARY_DETAIL = 'ANNIVERSARY_DETAIL'
export const ANNIVERSARY_SAVE = 'ANNIVERSARY_SAVE'
export const ANNIVERSARY_UPDATE = 'ANNIVERSARY_UPDATE'